import sys
import os
from snakemake.utils import validate

validate(config, schema="../config/schemas/config.schema.yaml")

python = sys.executable or "python3"

rule all:
    input:
        llama_script = os.path.join( config["output"], "llama_script.sh" )

# Include rules for download input files
include: "rules/downloads.smk"

# Include rules for preparing the alignment, metadata, and large tree to be used as input
# for llama.
include: "rules/prepare_tree.smk"

# Include rules for subsampling large tree.
#include: "rules/subsample_tree.smk" 

