import sys
import os
from snakemake.utils import validate

validate(config, schema="../config/schemas/config.schema.yaml")

python = sys.executable or "python3"

rule all:
    input:
        alignment = os.path.join( config["output"], "masked.fasta" )
        #cleaned_tree = os.path.join( config["output"], "input/global.tree" ),
        #cleaned_md = os.path.join( config["output"], "input/metadata.csv"),
        #cleaned_alignment

include: "rules/prepare_tree.smk"

