output: "/gpfs/home/natem/analysis/2020.10.30_hcov"
gisaid_seqs: "/gpfs/home/natem/analysis/2020.10.30_hcov/sequences_2020-10-29_07-32.fasta"
gisaid_md: "/gpfs/home/natem/analysis/2020.10.30_hcov/metadata_2020-10-29_08-57.tsv"
include: "resources/include_mb.txt"
exclude: "resources/exclude.txt"
reference: "MN908947"
email: "natem@scripps.edu"
focus: "division:California,Arizona,Texas,New Mexico;country:Mexico"

combine_data:
  country_codes: "resources/country_codes.csv"

filter:
  min_length: 25000
  exclude_where: "division='USA' date='2020' date='2020-01-XX' date='2020-02-XX' date='2020-03-XX' date='2020-04-XX' date='2020-05-XX' date='2020-06-XX' date='2020-07-XX' date='2020-08-XX' date='2020-09-XX' date='2020-10-XX' date='2020-11-XX' date='2020-12-XX' date='2020-01' date='2020-02' date='2020-03' date='2020-04' date='2020-05' date='2020-06' date='2020-07' date='2020-08' date='2020-09' date='2020-10' date='2020-11' date='2020-12'"
  group_by: "division year month"
  sequences_per_group: 2000
  min_date: "2019-12-01"

partition_sequences:
  sequences_per_group: 300

mask:
  vcf: "resources/mask.vcf"

collapse_polytomies:
  tree_url: "https://raw.githubusercontent.com/roblanf/sarscov2phylo/master/ft_SH.tree"
  limit: 0.00003

run_llama:
  input_column: "strain"
  summarize: "country"
